# Generated by Django 5.2.17 on 2026-09-30 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('neshan_poi_id', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='model', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.itinerary')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('sight', 'بازدید'), ('food', 'غذا'), ('transport', 'جابجایی'), ('rest', 'استراحت'), ('accommodation', 'اقامت'), ('other', 'سایر')], default='other', max_length=20)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.itineraryday')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.placecandidate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=64)),
                ('status', models.CharField(choices=[('collecting_info', 'در حال تکمیل اطلاعات'), ('ready_for_generation', 'آماده تولید برنامه'), ('generating', 'در حال تولید برنامه'), ('planned', 'برنامه\u200cریزی شده'), ('archived', 'بایگانی\u200cشده')], default='collecting_info', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'در صف'), ('running', 'در حال اجرا'), ('succeeded', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_jobs', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='placecandidate',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_candidates', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trips.trip'),
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trips.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('nightly_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('source', models.CharField(default='model', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.placecandidate')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('children_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_older_adults', models.BooleanField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('intercity_transport', models.CharField(choices=[('flight', 'هواپیما'), ('train', 'قطار'), ('bus', 'اتوبوس'), ('personal_car', 'خودروی شخصی'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('local_transport', models.CharField(choices=[('public_transit', 'حمل\u200cونقل عمومی'), ('taxi', 'تاکسی/اسنپ'), ('rental_car', 'اجاره خودرو'), ('walking', 'پیاده'), ('mixed', 'ترکیبی'), ('unknown', 'نامشخص')], default='unknown', max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('pace', models.CharField(blank=True, choices=[('relaxed', 'آرام'), ('balanced', 'متعادل'), ('intense', 'فشرده')], max_length=10, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('budget_scope', models.CharField(blank=True, choices=[('per_person', 'هرنفر'), ('group', 'کل گروه')], max_length=10, null=True)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('has_existing_accommodation', models.BooleanField(blank=True, null=True)),
                ('accommodation_notes', models.TextField(blank=True)),
                ('room_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nightly_accommodation_budget', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='trips.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['owner'], name='trips_trip_owner_i_fedb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['guest_session_key'], name='trips_trip_guest_s_fb6ef2_idx'),
        ),
    ]
