# Generated by Django 5.2.17 on 2026-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecandidate',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
